### ISSUE TITLE
Feedback for V0.1

### ISSUE THREAD

**Issue by brandonyeoxg** [CS2103JAN2017-F12-B2/main#21]
I noticed that your project title in the readme is still Addressbook 4 (Level 4)?
Your travis ci badge is unknown perhaps due to the change in the organisation name?
Please update the rest of the badges especially coveralls for the later milestones.
Perhaps the `Learning Outcomes` can be removed link.
Recall from tutorial that it would be better to pre-plan for all of your milestones =).
Please close this issue after reading.

**Comment by jjingrong** [comment]
@brandonyeoxg 

Got it!
