### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by brandonyeoxg** [CS2103JAN2017-F12-B2/main#92]
**Regarding User Guide:**
Good job updating how the GUI of the product will look like.
Perhaps you guys can look into adding partial screenshots capturing the use of your command(s)?

The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

**Regarding Developer Guide:**
Good job adding a comprehensive product survey, perhaps it can be represented in a table?

Do make sure the the diagrams are updated to represent your task manager and not the addressbook.

_For the user stories:_
Good job having comprehensive user stories. 
Perhaps task could be split into the three categories? Floating, deadline and event(start time and end time)? 

_For the use cases:_
Under `Use Case ends` I believe it should be on a new line by itself, do modify for all of your use cases.

_For the NFRs:_
Recall from tutorial that it should not be that vague like `Good OOP principles` and so on. It should be tangible like `Should execute within 0.5s`.

_For the glossary:_
Do make the appropriate modifications to it. Is `Private contact detail` really in the task manager?

It may be more practical to give a few examples of interesting test cases and explain the thinking behind how you arrived at those test cases, rather than try to give a comprehensive list of all test cases.

Perhaps explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.

**Overall**
Recall from tutorial about dog-fooding your product, perhaps think of ways to improve the command format?
Also try to do a peer review on each other's PR.
Please close this issue after reading it.

**Comment by jjingrong** [comment]
### For your reading

@benwongwf @huanhock 

---

Thanks @brandonyeoxg ! Will keep your feedback in mind moving forward
